### ISSUE TITLE
Something wrong when I want to train the structure prediction model

### ISSUE THREAD

**Issue by Jacky749** [sinc-lab/miRe2e#1]
I tried the command in the example, but it didn't work. First, it said it required a NVIDIA driver.
![image](https://user-images.githubusercontent.com/79360737/173318430-d6cd9b79-c55c-469f-84a2-78289b693c68.png) 
But even I changed to another server, it still had something wrong.
![image](https://user-images.githubusercontent.com/79360737/173321197-06edefc6-e90a-4495-b503-40dd8ea71fb5.png)
I don't know how to solve this problem. Could you help me?

**Comment by lbugnon** [comment]
Thanks for raising the issue! 

The first error seems to be related with pytorch/cuda installation, check https://pytorch.org/. By default, the package install one version of pytorch, but it may not work if the system CUDA Installation is different. It is better to install/configure pytorch correctly, then install the package.

The second error should be fixed now. It is important to specify the type of device used (either 'cpu' or 'cuda' for gpu). By default, MiRe2e object is created to use cpu only. If the server has at least one GPU, you need to pass the parameter device='cuda'. You can select a specific device, i.e. device='cuda:1' if you to have two  GPUs and you want to use the second one. 

i've  updated the readme  with this. Let me know if it works. Please install from this source with the following, i'll update the python package later 

```
git clone git@github.com:sinc-lab/miRe2e.git
cd miRe2e
pip install .
```

**Comment by Jacky749** [comment]
Thanks for your help! It works! But there is a new problem:
![image](https://user-images.githubusercontent.com/79360737/173560681-70f1b885-0c8b-4fa9-b30e-1c5d3aaa4a29.png)
I thought it may beacuse that there are too many sequences in the 'hairpin_examples.fa'. So I extracted some sequence of the example fasta file to test again, but it still don't work.
![image](https://user-images.githubusercontent.com/79360737/173561228-3ee6325a-48ec-4126-930f-eb414bc85e28.png)

**Comment by lbugnon** [comment]
Calling that with the full file takes about 8gb of GPU's ram in setup. You can use a smaller batch size (by default is 512). For example with 64 memory is reduced to 2.5gb


`model.fit_structure('hairpin_examples.fa', batch_size=64)
`

The second error was unexpected, it happens when the number of sequences is lower than the batch size. Thanks to point it out. I'll fix it now. In the meantime, you can use a lower batch_size and it should work.

**Comment by Jacky749** [comment]
Thanks for your reply! I tried this command ‘model.fit_structure('hairpin_examples.fa', batch_size=64)’, and it worked. But this command didn't support the fasta file with less sequences:
![image](https://user-images.githubusercontent.com/79360737/173810380-2170ba96-a169-4308-acb3-39c0487f7d65.png)

**Comment by lbugnon** [comment]
Yes, in the last commit I added some descriptions to errors. In this case, batch size should be in the range [1, Nsequences/10]. This is because is assumed that a large number of sequences are being used for training (let say at least 10k) 

If you want to use the predictor as it is, please follow the example in the [miRe2e notebook](https://colab.research.google.com/drive/1k_4T4a5i79SQ3cQEEfCmgY_jp7RkLQ8b) 

scores_5_3, scores_3_5, index = `model.predict(filename, batch_size=64)`

In that case, filename can have any number of sequnces, and batch size will balance hardware availability and speed

**Comment by Jacky749** [comment]
Thanks for your help again! The problems we disscussed have been solved.
Referring to the miRe2e notebook, I followed the examples and it worked with lower batch size. 

But I want to train a new model with my own sequences, and use this model to find similar sequences in other genomes. These sequences can form hairpin structure, but are not belong to miRNA family. So I can't directly take the 'positive_examples.fa' as trained model. The structure prediction model and MFE estimation model can work well with my own sequences. But the pre-miRNA classifier can't. I renamed my own sequences as the sequences name in 'positive_examples.fa‘. However it still didn't work. What is the positive_examples.fa require? Can I use miRe2e to train a non-miRNA model?
![image](https://user-images.githubusercontent.com/79360737/174283424-909fc583-6d5f-468a-9dc3-772f61d291e5.png)

**Comment by lbugnon** [comment]
@Jacky749 sorry for the delay. Yes, you definatelly can use the model to train for other tasks. If the sequences are hairpin-like, then you could use the structure and MFE as it is. 

To train the final predictor, you will need both positive and negative class sequences for your task. It is important to have several sequences (I don't know how many of them, but surely more than 1,000). Please try to pull again the repo, the error may be due to a training file too short (it should be fixed). Otherwise, you could send me a sample file so I can find the issue

**Comment by Jacky749** [comment]
Thanks for your reply! I am afraid that I don't have enough number of positive class sequences. But I noticed that there is a small set of identical sequences in the postitive_examples. If I can make multiple duplication of my own sequences to obtain enough number of postitive_examples.

Attached is my postitive_examples file.
[3species.with_secondary_Structure.zip](https://github.com/sinc-lab/miRe2e/files/8975099/3species.with_secondary_Structure.zip)

**Comment by lbugnon** [comment]
@Jacky749 given that number of sequences is low, you could use a batch size = 4  (the training should be fast, it is not needed to repeat sequences in the file). Then you could check if the model is finding the known positives of your task before using it in new sequences

**Comment by Jacky749** [comment]
Thank you! It works! But the final output is not satisfactory. I noticed that the default window length of index is 100bp in this example (https://colab.research.google.com/drive/1k_4T4a5i79SQ3cQEEfCmgY_jp7RkLQ8b#scrollTo=cTRnn7-ZJxEv). Because the length of my positive hits is only about 40bp, this parameter may be not suitable in my case. Could I change the length to 40bp? Where could I change this parameter?

**Comment by lbugnon** [comment]
The window length is the maximum used by the model. If the sequence is shorter, it is padded with zeros. You should build a negative dataset with sequences of similar length (~40bp) to train the model. Otherwise, the model may "cheat" and learn that shorter sequences are the positive class. Hope it works!

**Comment by Jacky749** [comment]
I am sorry about that the sequences in negative dataset are all around 40bp. But the window length is still 100bp. Is there any solution to change the window length manually?

**Comment by Jacky749** [comment]
I am sorry about that the sequences in negative dataset are all around 40bp. But the window length is still 100bp. Is there any solution to change the window length manually?

**Comment by lbugnon** [comment]
Yes, the "fit" function have a parameter "length" to adjust this
